# Generated by Django 5.1.4 on 2025-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCompressLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('original_size', models.BigIntegerField()),
                ('compressed_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('compressed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File Compression Log',
                'verbose_name_plural': 'File Compression Logs',
                'ordering': ['-compressed_at'],
            },
        ),
    ]
